### ISSUE TITLE
Generate client certificates for auth

### ISSUE THREAD

**Issue by kofalt** [scitran/scitran#10]
We already generate a self-signed certificate + key for debug SSL purposes.
As various applications (such as the reaper) auth with client certs, we should help create them.

My current understanding of non-ruinous self-signed client certs:

```bash
# Generate private key
openssl genrsa -out client.pem 4096

# Generate CSR (spam stdin for prompts)
openssl req -new -sha256 -key client.pem -out client.csr

# Information about the CSR (debug)
openssl req -noout -text -in client.csr

# Sign yourself a CA (spam stdin for prompts)
openssl req -new -x509 -key client.pem -out client.ca.pem

# Sign your CSR with your CA
openssl x509 -req -in client.csr -CA client.ca.pem -CAkey client.pem -set_serial 01 -out client.crt
```

It is not clear to me if nginx can tolerate multiple CA entry points. An optimal approach would use one CA per authorized actor, so as to revoke them individually - basically treating them like API keys - without  the normal insanity that SSL CA revocation usually entails.

We currently point nginx to `ssl_client_certificate  /etc/ssl/certs/ca-certificates.crt;`. Perhaps a small script that on each boot looks at `/etc/nginx/keys` (via our mount point), cats them together with `/etc/ssl/certs/ca-certificates.crt` to a temp file and uses that?

**Comment by kevlarkevin** [comment]
would using [ssl_trusted_certificate](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_trusted_certificate) be an option?  I haven't tried this myself, so I'm certain it is what you need.  Just wanted to throw it on the table.

**Comment by kofalt** [comment]
I think so, but I'm wondering how it behaves with multiple files.
See above comments on ideally using a CA per application.

I suppose we can just immediately generate two & see what happens.

**Comment by kofalt** [comment]
Which reminds me, the `scritran.py addClient` target or w/e should take an app name, and all these files can be called `client-name.*` such that they're clearly identified.

**Comment by kofalt** [comment]
A quick test confirms that nginx tolerates duplicates of neither `ssl_client_certificate` nor
`ssl_trusted_certificate`, so the entry point being a bash script that runs `cat /etc/ssl/certs/ca-certificates.crt /etc/nginx/client-*.ca.pem > /tmp/ssl-certs` is probably the correct way forward.

**Comment by kofalt** [comment]
I've pushed some experimentation to [client-certs](https://github.com/scitran/scitran/compare/test-config...client-certs) that has an example of running a quick setup script. 

I still haven't been able to auth to the API with a client certificate successfully; maybe someone else can lend a hand?

**Comment by kofalt** [comment]
This has been resolved by `./live.sh create-drone`; much work remains but will be expressed in different tickets.
