### ISSUE TITLE
Unattended flag for scitran.py

### ISSUE THREAD

**Issue by kofalt** [scitran/scitran#11]
Currently, `scitran.py start` should never prompt the user as long as these files exist:

* `config.toml`
* `key+cert.pem`
* `persistent/mongo/mongod.lock`

All of which would be expected to exist on a previously-created, healthy instance. However, it would be pretty reasonable to just throw `scitran.py start` in an init script some where, and hanging at a prompt where they're no TTY is the Wrong Thing To Do.

We should add a global flag `--unattended` or similar, that will hard-exit the script whenever there would be a prompt. Easily accomplished by setting a global boolean and having each prompt call go through a function that checks it.

**Comment by kevlarkevin** [comment]
this is already in the works.

**Comment by kofalt** [comment]
Aces :)

**Comment by kofalt** [comment]
This has been obviated by the new infrastructure: `./live.sh` has no prompts excluding `sudo` for install.

We'll work with @lmperry to decide what requirements / additions production deployments require.
