### ISSUE TITLE
Can't start new instance - missing directory

### ISSUE THREAD

**Issue by xoltar** [scitran/scitran#26]
Hi Folks,

When installing the source version according to https://github.com/scitran/scitran documentation, I get the failure below. This is on Ubuntu 14.04.

Connecting to docker...
Copying key+cert.pem into api and nginx bind mount locations
Copying root cert file into nginx bind mount location
generating code/sdm/app/config/default/config.js from scripts/templates/config.js x config.toml
Traceback (most recent call last):
  File "./scitran.py", line 1040, in <module>
    args.func(args)
  File "./scitran.py", line 740, in start
    generate_from_template(CONFIGJS_IN, CONFIGJS_OUT, nginx['fullName'], api['fullName'], mongo['fullName'])
  File "./scitran.py", line 361, in generate_from_template
    os.mkdir(outdir)
OSError: [Errno 2] No such file or directory: 'code/sdm/app/config/default'

**Comment by kofalt** [comment]
My @xoltar - thanks for filing these tickets and PR!

We know we have some trouble on the install side right now: for context, I'm currently working on dramatically simplifying our initial setup. I'll defer to @lmperry for your current contributes, and soon (ideally within a week or so) we'll have a different way to spin up a scitran instance.

**Comment by kofalt** [comment]
An update: We now have a completely new way of spinning up scitran, with a lot less muss and fuss. You can install on any Ubuntu 64-bit host, or use the included vagrant file.

Mind giving that a spin? I recommend an entire new git clone.

If it works I'd like to think that this ticket, #27, and #28 can all be closed.

**Comment by kofalt** [comment]
Closing as per the above comments; the new infrastructure removes this problem entirely. If you have issues on the tip of master, it can be a separate ticket & we'll deal with it there :)
