### ISSUE TITLE
Bootstrapping data does not work on master

### ISSUE THREAD

**Issue by josschne** [scitran/scitran#29]
Attempting to bootstrap data with 

    $ sudo ./scitran.py bootstrap --data

The script attempts to upload the files, but they each fail. Switching the code/api/ repo to the "demo" branch fixes the issue.  Likely we missed this when updating to the api to the new upload method.

**Comment by gsfr** [comment]
This is actually not a legitimate way of getting data into scitran. It uses the reaper's backdoor, which of course needs to be locked down (with two-way SSL) asap. The right way to get data in is by running a maintenance container and calling ```api/bootstrap.py sort -q```.
@lmperry - Could you please add instructions here?
I don't think it's worth changing scitran.py right now as we seem to be moving away from it. Just say no when you are asked about bootstrapping data.

**Comment by lmperry** [comment]
To bootstrap (sort) data I do the following: 
- Move the data (dicom.tgz files) to be sorted into the persistent data directory (so the maintenance container can access it)
- Start a maintenance container
- Run the `boostrap.py sort` command

```
# Move the data into place
mkdir persistent/data/sort
mv dataToSort/* persistent/data/sort

# Start the maintenance container
./scitran.py maintenance # Execute resulting command to start the maintenance container

# Run the boostrap.py sort command in the maintenance container
cd /service/code/api
./bootstrap.py sort mongodb://mongo/scitran /persistent/data/sort/ /persistent/data -q
```

* Also see `./bootstrap.py sort -h`

**Comment by gsfr** [comment]
```api/bootstrap.py upload``` is fixed, but ```scitran.py``` did not work for us just now on a fresh GCE Debian VM, running docker 1.7 and docker 1.6.2. Different errors on the two docker version, though. However, everything worked fine on a baremetal Ubuntu, running docker 1.6.2.
