### ISSUE TITLE
Q: Cannot connect to configured scitran server

### ISSUE THREAD

**Issue by Eric89GXL** [scitran/scitran#3]
I have tried setting up Scitran on my local system two ways. Using the release version, I get:
```Python
larsoner@bunk:~/python/scitran-release$ ./scitran.py start
Starting scitran...

It looks like this is a new scitran instance. Would you like to add some data? 
If so, enter a valid Google email for your first user: larson.eric.d@gmail.com

Connecting to docker...
Confirming any previous scitran is stopped...
Stopping previous mongo...
Generating config files...
Starting scitran...
Recreating scitran_mongo_1...
Recreating scitran_api_1...
Recreating scitran_nginx_1...
Adding initial data and user larson.eric.d@gmail.com...
Traceback (most recent call last):
  File "./scitran.py", line 383, in <module>
    run()
  File "./scitran.py", line 379, in run
    args.func(args)
  File "./scitran.py", line 337, in start
    bootstrapData(config, docker, api["fullName"], mongo["fullName"], email)
  File "./scitran.py", line 239, in bootstrapData
    os.path.join(os.getcwd(), 'code'):        {'bind': '/service/code',   'ro': False },
  File "/home/larsoner/.local/lib/python2.7/site-packages/docker/client.py", line 867, in start
    self._raise_for_status(res)
  File "/home/larsoner/.local/lib/python2.7/site-packages/docker/client.py", line 95, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Could not get container for None")
```

Using the development version, I get farther:
```Bash
larsoner@bunk:~/python/scitran$ sudo ./scitran.py start
Starting scitran...

Connecting to docker...
Confirming any previous scitran is stopped...
Stopping previous mongo...
Generating config files...
Starting scitran...
Recreating scitran_mongo_1...
Recreating scitran_api_1...
Recreating scitran_nginx_1...

Check out your running site at https://localhost
Scitran is running!
larsoner@bunk:~/python/scitran$ 
```
...but cannot connect to `https://127.0.0.1` in a browser. `sudo netstat -tulpn` and associated commands confirm that the ports aren't open, too. Any ideas on where to start debugging?

At one point I had `nginx` installed and running locally, but I didn't see an easy way to get it to use my local version instead of the docker version. When I have it running (with confirmation from `netstat` that it is listening to requests), I do get a nice, expected error suggesting that `scitran` is trying to open ports:
```
larsoner@bunk:~/python/scitran$ sudo ./scitran.py start
Starting scitran...

Connecting to docker...
Confirming any previous scitran is stopped...
Generating config files...
Starting scitran...
Recreating scitran_mongo_1...
Recreating scitran_api_1...
Recreating scitran_nginx_1...
Cannot start container 02437fa029e3a29a40286498525ed5eea64f98a4bd56d65d6f33d832a06367d6: Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
Traceback (most recent call last):
...
```
But I'm not sure why, when my local `nginx` is stopped, the `scitran` ports don't stay open... maybe I'm being dense here. Let me know if there are places I should look to debug.

**Comment by kofalt** [comment]
As a side note: using https://localhost will work for auth rather than 127.0.0.1 if you're using our default Google auth (ping @kevlarkevin if you have questions on that part, has to do with how Google handles authentication URIs).

Also as a side note, we use 80, 443, and 8080. Actively looking to eliminate that last one.

The first thing I'd do is start from scratch (a clean copy of the tarball) on the release version, and make a [gist](http://gist.github.com) of the logs in `data/log`, which is where all container logs will end up.

If there's nothing incriminating in there, you might try running the nginx container manually to see what's up. For me it would be something ugly like:

`docker run -it -v /home/kofalt/z/scitran/nginx:/etc/nginx -v /home/kofalt/z/scitran/data/log:/service/log -v /home/kofalt/z/scitran/code/sdm/app:/service/web scitran-nginx:0 /bin/bash`

Replace `/home/kofalt/z/scitran/` with the absolute path of your scitran folder)

Then run `nginx` and paste the output (if any) here.

Hope this helps!

**Comment by Eric89GXL** [comment]
Great, thanks for the quick response.

On a clean tarball of the release, as before, I get this:
```
Connecting to docker...
Confirming any previous scitran is stopped...
Generating config files...
Starting scitran...
Recreating scitran_mongo_1...
Recreating scitran_api_1...
Recreating scitran_nginx_1...
Adding initial data and user larson.eric.d@gmail.com...
Traceback (most recent call last):
...
  File "./scitran.py", line 239, in bootstrapData
    os.path.join(os.getcwd(), 'code'):        {'bind': '/service/code',   'ro': False },
  File "/home/larsoner/.local/lib/python2.7/site-packages/docker/client.py", line 867, in start
    self._raise_for_status(res)
  File "/home/larsoner/.local/lib/python2.7/site-packages/docker/client.py", line 95, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Could not get container for None")
```
But oddle enough `data/log` is empty.

On a clean dev version, I get the same error, but I actually get a populated `data/logs/api.log` (full gist https://gist.github.com/Eric89GXL/9de4b736b04c37b8f990) that ends with:
```
...
mapped 249168 bytes (243 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
usage: uwsgi [-h] --db_uri DB_URI --data_path DATA_PATH --ssl_cert SSL_CERT
             [--api_uri API_URI] [--site_id SITE_ID] [--site_name SITE_NAME]
             [--oauth2_id_endpoint OAUTH2_ID_ENDPOINT] [--demo] [--insecure]
             [--central_uri CENTRAL_URI] [--log_level LOG_LEVEL]
uwsgi: error: argument --db_uri is required
```
Running `nginx` manually I get:
```
larsoner@bunk:~/python/scitran$ docker run -it -v /home/larsoner/python/scitran/nginx:/etc/nginx -v /home/larsoner/python/scitran/data/log:/service/log -v /home/larsoner/python/scitran/code/sdm/app:/service/web scitran-nginx:0 /bin/bashroot@ac7c47cafd77:/# nginx
2015/02/27 23:49:00 [emerg] 5#0: host not found in upstream "api" in /etc/nginx/nginx.conf:64
nginx: [emerg] host not found in upstream "api" in /etc/nginx/nginx.conf:64
```

**Comment by Eric89GXL** [comment]
The manually run `nginx` call failure is probably due to it looking for `uwsgi` (line 64 in the conf), but it has failed to load...?

**Comment by kofalt** [comment]
It looks like you'll need the fake FQDN `mongo` to resolve in order for nginx to start. This is an irritating property of nginx where it'll refuse to start if an upstream name does not resolve in DNS. 

If you run either release or development with `./scitran.py start`, and then try a `docker ps`, I suspect you'll find that two containers are running (API and Mongo) but lacking nginx.

While those two containers are running, add the Mongo container ID as a link with name mongo. So if docker says the mongo container's ID is `46d7f272f4a2`, add `--link 46d7f272f4a2:mongo` to your `docker run` command, before the `scitran-nginx:0 /bin/bash` bit.

This will allow nginx to actually try & launch, and hopefully get the real error out.

**Comment by Eric89GXL** [comment]
Looks like I only get a single docker instance running actually:
```
larsoner@bunk:~/python/scitran$ ./scitran.py start
Starting scitran...

Connecting to docker...
Confirming any previous scitran is stopped...
Stopping previous mongo...
Generating config files...
Starting scitran...
Recreating scitran_mongo_1...
Recreating scitran_api_1...
Recreating scitran_nginx_1...

Check out your running site at https://localhost
Scitran is running!
larsoner@bunk:~/python/scitran$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
64b73c444d83        scitran-mongo:0     "mongod"            About a minute ago   Up 59 seconds       21707/tcp           scitran_mongo_1
```
And so I don't think this error is surprising:
```
larsoner@bunk:~/python/scitran$ docker run -it -v /home/larsoner/python/scitran/nginx:/etc/nginx -v /home/larsoner/python/scitran/data/log:/service/log -v /home/larsoner/python/scitran/code/sdm/app:/service/web --link 64b73c444d83:mongo scitran-nginx:0 /bin/bash
root@3760b722286f:/# nginx
2015/03/02 16:55:04 [emerg] 5#0: host not found in upstream "api" in /etc/nginx/nginx.conf:64
nginx: [emerg] host not found in upstream "api" in /etc/nginx/nginx.conf:64
```

**Comment by kofalt** [comment]
Oh geez, I completely mis-remembered which containers link to which.
So the API container is crashing on start as well, pinging @kevlarkevin for that.

If you prefer, we can maybe set up a real time debugging session; we haven't had many folks try to spin up our software yet :)

**Comment by Eric89GXL** [comment]
If that's easier for you all, sure. Whatever minimizes the time drain we put on you for debugging...

**Comment by kofalt** [comment]
Can you try out the `new-deploy` branch? 
Kevin is sick today but created a branch ([see compare](https://github.com/scitran/scitran/compare/new_deploy)) that has a lot of changes on it. 

I suspect the release tarball is not currently matched with what's on master, our bad :(

**Comment by kevlarkevin** [comment]
@Eric89GXL Sorry for the mixup. Blame me.

The clean install isn't working because the release file doesn't contain the data needed to bootstrap the installation.   We'll have to make sure the next release comes bundled with the data.  Can you try running `git clone https://github.com/scitran/testdata.git code/testdata`? 

Regarding development install not working: I broke the development install while make changes elsewhere.  The API is being started in a different way, and the current install script doesn't work for those changes.   Can you try installing using the `new-deploy` branch?

**Comment by Eric89GXL** [comment]
Removed old `scitran` directory and did:
```Bash
$ git clone git://github.com/scitran/scitran.git
$ cd scitran
$ git checkout -b new_deploy origin/new_deploy
$ wget https://storage.googleapis.com/scitran-dist/release.tar
$ tar -xf release.tar bin/ containers/
$ git clone https://github.com/scitran/api.git      code/api
$ git clone https://github.com/scitran/data.git     code/data
$ git clone https://github.com/scitran/sdm.git      code/sdm
$ git clone https://github.com/scitran/testdata.git code/testdata
$ ./scitran.py start

<enter at all prompts except email: larson.eric.d@gmail.com>

Connecting to docker...
Confirming any previous scitran is stopped...
Generating config files...
Starting scitran...
Recreating scitran_mongo_1...
Recreating scitran_api_1...
Recreating scitran_nginx_1...
Adding initial data and user larson.eric.d@gmail.com...
Traceback (most recent call last):
  File "./scitran.py", line 378, in <module>
    run()
  File "./scitran.py", line 374, in run
    args.func(args)
  File "./scitran.py", line 332, in start
    bootstrapData(config, docker, api["fullName"], mongo["fullName"], email)
  File "./scitran.py", line 234, in bootstrapData
    os.path.join(os.getcwd(), 'code'):        {'bind': '/service/code',   'ro': False },
  File "/home/larsoner/.local/lib/python2.7/site-packages/docker/client.py", line 867, in start
    self._raise_for_status(res)
  File "/home/larsoner/.local/lib/python2.7/site-packages/docker/client.py", line 95, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Could not get container for None")
```
If I re-run `./scitran.py start` I no longer get the error, but still can't connect to `https://localhost`.

I tried starting from scratch and running the start command as `sudo` and it didn't make a difference.

**Comment by kevlarkevin** [comment]
@Eric89GXL I'm working on some fixes and things in the new-deploy branch.  It will be ready for you by tomorrow morning.  

Can we plan to do a joint tmux-session, google hangout or something to get you up and running?

**Comment by Eric89GXL** [comment]
Sure. I could also try spinning up an Ubuntu VM to see if I can reproduce the issue, that way you'd have something to test off of locally easily.

**Comment by kevlarkevin** [comment]
Are you currently running with boot2docker?

**Comment by Eric89GXL** [comment]
I am running docker.io on Ubuntu 14.10

**Comment by Eric89GXL** [comment]
Resolved via chat; mis-placement of the key cert file. @kevlarkevin is working on a fix. Thanks for the help everyone!
