### ISSUE TITLE
Improve bootstrap.json behaviour

### ISSUE THREAD

**Issue by kofalt** [scitran/scitran#37]
* Add target that prompts for username + email and saves that to bootstrap

When bootstrapping: 

* If git config is valid and template is unmodified, use their git name and email
* If git config is invalid and template is unmodified, run prompt target
* Else, use modified bootstrap template

Print summary of action taken and how to reset to clean database.

**Comment by lmperry** [comment]
Sounds good. The other thing to consider is that while the git config may be valid, the email used therein may not be compatible with google auth. May need to check that it's a gmail address and if not prompt, or have the user confirm. This has come up with some users who bootstrap their email address only to find out later that google can't authenticate them.

**Comment by kofalt** [comment]
Google auth is valid for arbitrary domains, so a regex won't tell us which. As part of this ticket the summary should make it clear what email was attempted & that what you might need to do.

**Comment by gsfr** [comment]
I think we are actually doing fine with our current interactive solution. What we need now is an obvious way to support a custom ```bootstrap.json``` file, as outlined in #50.

**Comment by kofalt** [comment]
That's good - I've wanted to close a couple of these tickets for awhile.
