### ISSUE TITLE
Remove demo functionality references

### ISSUE THREAD

**Issue by kofalt** [scitran/scitran#54]
* Remove `site.demo` from config
* Find / remove any other references
* Bump config version; document

**Comment by Eric89GXL** [comment]
Ahh yes, I just tried to set `demo = true` for testing purposes, and the Python interpreter quit:
```
Python:   Running
Mongo:    Running
Nginx:    Running
Python:   (error exit: exit status 2)
```
I can probably tackle this with a quick `git grep`

**Comment by kofalt** [comment]
Whenever that happens, try `./live.sh tail-python` and restart the service (quit the script and re-run it).

Let me know if there's an interesting stack trace, we can chat about it in a separate bug :)
I'll add that tip to troubleshooting documentation also.
