### ISSUE TITLE
BUG: Using system-level `nginx` log

### ISSUE THREAD

**Issue by Eric89GXL** [scitran/scitran#59]
I get an error on starting `./live.sh run`:
```
Nginx:    nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
```
It seems like `scitran` shouldn't configure `nginx` to access that log file at all, but it must be doing so somewhere. Any ideas where to debug?

**Comment by Eric89GXL** [comment]
For now I can work around it by doing `sudo rm -Rf /var/log/nginx/*` (then the user-level `./live.sh run` will create its own files and be good), but I have to do this after every reboot because by default `nginx` spins up an instance and recreates the inaccessible log files.

**Comment by kofalt** [comment]
Agreed, this is a known issue and has been irritating me for some time. Nginx is configured to use `persistent/logs/nginx-*`, but will demand creating a zero-byte log file in the system default location.

Compiling nginx from source (ref the source-infra PR, currently stalled) solves the problem, but I would assume there's another way. Check out the nginx template - got any ideas?

**Comment by Eric89GXL** [comment]
Ahh, yeah I was worried it might be a big at their end. The fact that
compiling from source fixes it suggests it's a bug they have fixed, too.
I'll take a look at the configuration bit I'm not too optimistic

**Comment by kofalt** [comment]
Sounds good. It might also be solvable by changing the launch flags. For example, if there's a syntax error with the configuration file it's logged to the system log file, but the folder prefix is already set, so I'm not sure. Ref the reflex template to see launch flags :)

**Comment by Eric89GXL** [comment]
I worked around the issue by creating an `error.log` with my current user's permissions. Seems to work okay. I'll go ahead and close this since the bug is most likely with upstream software (nginx).
