### ISSUE TITLE
Client certificates cause poor UX

### ISSUE THREAD

**Issue by kofalt** [scitran/scitran#8]
Based on your browser configuration (and unconditionally in Safari), you may receive confusing prompts while accessing the user interface or API.

Ideally, we would have a separate route, header, etc to indicate to nginx that you wish to attempt client certificate authentication, and thus keep it away from the UI. This may or may not be easy with the way nginx thinks about client cert auth.

**Comment by gsfr** [comment]
As I learned yesterday, this can happen on Chrome as well. We should probably make a plan for having a browser API and a machine API. I'll look into nginx config.

**Comment by kofalt** [comment]
This is obsoleted by using a separate port for client certs.

We can revisit the larger issue of client cert auth separately.
