### ISSUE TITLE
fail bootstrap

### ISSUE THREAD

**Issue by 35takao** [scitran/scitran#83]
Hello,

I have failed in the step of bootstrap (./live.sh bootstrap).
I succeeded install and login when I first tried to use scitran in November .
This time, I am trying to remake the scitran environment and failed.

The output log I got is as follows. Sorry, but long.
--->
$~/scitran$ ./live.sh setup
.....
Flywheel: Generated server certificate
Flywheel: Your shared secret is: 3fb61c1bd1b140a6ab8feb73e5273622

Setup complete! You should now edit config.toml to configure your instance.
After that, continue with: ./live.sh bootstrap and or ./live.sh run

$~/scitran$ ./live.sh bootstrap
Flywheel: Bootstrapping users and test data
Flywheel: Preparing infrastructre for bootstrap...
[00] Starting service
[01] Starting service
Flywheel: Reflex launched with 2120
[02] Starting service
Flywheel: Waiting for infrastructure to be ready for bootstrap...
[00] [uWSGI] getting INI configuration from persistent/generated/uwsgi.config.ini
[00] (error exit: exit status 1)
Flywheel: Setting up instance...
usage: bootstrap.py [-h] {clean,users,data} ...
bootstrap.py: error: invalid choice: 'configure' (choose from 'clean', 'users', 'data')
Flywheel: Bootstrapping users failed. Cleaning up...
Flywheel: Reflex stopping with 2120
Interrupted (interrupt). Cleaning up children...
[02] ^C
[01] ^C
<---

I tried that on Ubuntu14.04LTS, Ubuntu14.04LTS on virtualbox, Ubuntu15.04 on virtualbox (included in scitran).
I have followed the README.md, but what did I do something wrong?

I haven't found the part where "configure" option is defined for bootstrap.py.
Any help will be appreciate in advance.

**Comment by htakemur** [comment]
@35takao is working with me to install SciTran into the local computer in our sites. 
First thing I guess is that the error may be associated with the last commit (20 days ago?), because @35takao was successful in installing it just before. 

Thus, we already have some guess. Are there anybody having ideas?

**Comment by gsfr** [comment]
Hey guys, sorry for the delay. We have decided to no longer support scitran/scitran. Some recent commits to scitran/api that have broken compatibility with scitran/scitran. You have a couple of options, though: Either use the aloha branch of scitran/scitran or, if you have a Mac, use `bin/run.sh` from scitran/api. Even if you don't have a Mac, `run.sh` should not be hard to adapt to Ubuntu.

**Comment by 35takao** [comment]
Hi gsfr,
Thank you for responding. I tried aloha branch.
Although there were a few problems in the aloha branch, I solved them and then I succeeded to install scitran (aloha).

I appreciate your proper advice.
